server:
  servlet:
    context-path: /api-acceso-datos
  port: 5003

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tickets
    username: hashticket
    password: 12345678
  liquibase:
    change-log: classpath:/db/db.changelog.xml
    
